### ISSUE TITLE
Use custom build of CC:R

### ISSUE THREAD

**Issue by Merith-TK** [nitkit-mc/nitkit#1]
Hey so latest release of 1.18.2 CC:R has an small bug.

Computers are using the redstone properties of STONE, not GLASS, which *breaks* anything to do with redstone and CC:R (namely create stuff)

Please utilize either an source build (compile mod latest source code) or use the jar from https://git.merith.xyz/modpacks/ultron/src/branch/main/.minecraft/mods/cc-restitched-1.100.9-pre-release.jar

**Comment by EmmaKnijn** [comment]
We'll be using the jar from the link you sent

**Comment by Merith-TK** [comment]
Alright, that is the build I use on my server, it's litterally just the
redstone fix and an different fabric.mod.json for the version and title.

**Comment by EmmaKnijn** [comment]
Fixed as of https://github.com/nitkit-mc/nitkit/commit/eecdc02cd3e8dcff4a70e97b8a35c54e97a39e16
